#!/bin/bash
# Needs bash for PIPESTATUS

# die $EXITCODE $MESSAGE
# Print a message and exit with a given exit code.
die ()
{
    echo "$2" >&2
    exit $1
}

ROUTE=$1

echo "Getting route $ROUTE"

RID=$(grep "^[^,]*,[^,]*,${ROUTE},.*$" routes.txt | cut -d ',' -f1 ; exit ${PIPESTATUS[0]})
test $? -eq 0 || die 1 "Route short name not found in GTFS"
echo "route_id = $RID"

SHAPES=$(grep "^${RID}" shapes.txt | cut -d',' -f1 | sort -u ; exit ${PIPESTATUS[0]})
test $? -eq 0 || die 1 "route_id not found in shapes"
#echo "shapes = $SHAPES"

echo "Writing to GPX files..."
IFS=$'\n'
for SS in $SHAPES ; do
    OUTNAME=$(echo $SS | sed "s/^[^_]*/$ROUTE/")
    grep "^${SS}," shapes.txt | cut -d',' -f2,3 | gpsbabel -t -i unicsv,fields=lat+lon -f - -o gpx -F "${OUTNAME}.gpx"
    echo "${OUTNAME}.gpx"
    TRIPID=$(grep "^${RID},[^,]*,[^,]*,[^,]*,[^,]*,${SS},.*" trips.txt | head -1 | cut -d',' -f3 )
    test -n "$TRIPID" || die 1 "No trip_id found in trips.txt"
    #echo "Getting stops for trip_id = $TRIPID"
    STOPIDS=$(grep "^${TRIPID},.*" stop_times.txt | cut -d',' -f4 ; exit ${PIPESTATUS[0]})
    test $? -eq 0 || die 1 "trip_id not found in stop_times.txt"
    TFILE=$(tempfile)
    echo "${OUTNAME}_stops.gpx"
    for STOP in $STOPIDS ; do
        grep "^${STOP}," stops.txt >> "$TFILE"
        test $? -eq 0 || die 1 "stop_id $STOP not found in stops.txt"
    done
    cat "$TFILE" | cut -d',' -f2,3,5,6 | tr -d '"' | gpsbabel -w -i unicsv,fields=name+desc+lat+lon -f - -o gpx -F "${OUTNAME}_stops.gpx"
    rm -f "$TFILE"
done
